course: "Applied Computational Science II"

module_configs:
  - "config/intro.yml"
  - "config/pdes.yml"
  - "config/fft.yml"


window config:
  location: 
    - 0
    - 0
  size:
    - 500
    - 500
  finalize: True