module: "Fast Fourier Transforms"

location: "ffts/"

submodules:
  Recursive FFT: "recursive_fft.py"
  Twiddle Factors: "twiddle_factors.py"
  Padding Sequences: "padding_sequences.py"

text: "The following modules illustrate the FFT algorithm for\n\
computing the discrete Fourier transform and demonstrate\n\
applications of the DFT."
