module: "Fast Fourier Transforms"

location: "iea/acs2/ffts/"

submodules:
  Recursive FFT: "recursive_fft.py"
  Padding Sequences: "padding_sequences.py"
  Digital Filtering: "digital_filtering.py"

text: "The following modules illustrate the FFT algorithm for\n\
computing the discrete Fourier transform and demonstrate\n\
applications of the DFT."
