module: "Partial Differential Equations"

location: "iea/acs2/pdes/"

submodules:
  Laplace Equation: "laplace_eqn.py"
  Poisson Equation: "poisson_eqn.py"
  Heat Equation:    "heat_eqn.py"
  Wave Equation:    "wave_eqn.py"
  Multigrid:        "multigrid.py"

text: "The following modules illustrate various PDEs."
