module: "Partial Differential Equations"

location: "iea/acs2/pdes/"

submodules:
  Laplace Equation: "laplace_eqn.py"
  Heat Equation: "heat_eqn.py"
  Wave Equation: "wave_eqn.py"

text: "The following modules illustrate various PDEs."
